### ISSUE TITLE
关于进度条等建议

### ISSUE THREAD

**Issue by Yweiwu30** [OLDRedstone/EventCounter#8]
obs太强了
and 加载进度条/成就 when
&& readme第一个"（应该吧？"的"吧"打成"把"了（如果这也算是一种趣味性 当我没说）

**Comment by Yweiwu30** [comment]
还有 有没有一键全选所有事件的功能（

**Comment by OLDRedstone** [comment]
> 还有 有没有一键全选所有事件的功能（

呐，现在加入了选项卡左键反选，或许比全选更有用？（

**Comment by OLDRedstone** [comment]
进度条/成就已添加

**Comment by OLDRedstone** [comment]
另外，目前只加了2个成就的判定
